### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dladden** [onflowai/trendflow#55]
- [x] set the nav for small page in landing
- [x] clear saved trends for guest user after sign out (limit amount of trends can be saved)
- [x] fix blog page give space to tech / put them into a box
- [x] research more on gradient styles in svg modding
- [x] add the dark mode to landing
- [x] modify toastify finish styling and all pages
- [x] custom errors in controllers fix all
